- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Configure Nginx
  include_tasks: nginx.yml

- name: Configure Wireguard
  include_tasks: wireguard.yml

