- name: Nginx config
  template:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  register: nginx_config

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
  when: nginx_config.changed
  ignore_errors: true
